apiVersion: v1
kind: ConfigMap
metadata:
  name: vaulytica-config
  namespace: security
data:
  model-name: "claude-3-haiku-20240307"
  max-tokens: "4000"
  temperature: "0.0"
  enable-rag: "true"
  enable-cache: "true"
  max-historical-incidents: "5"
  batch-max-workers: "3"
  log-level: "INFO"

