/**
 * The clause each repaired conjunction asks for, and what the rule used to
 * demand instead. Shared by `compliant-conjunctions.test.ts`, which proves the
 * rule is silent on each, and by `pillar-vacuity.test.ts`, which treats a
 * collapsed conjunction as acceptable once it appears here.
 */
export const COMPLIANT: Array<[string, string, string, string]> = [
  [
    "ENG-002",
    "Engagement Letter",
    "Our client in this matter is Halstead Brothers Aggregates, LLC only. We do not represent its members, officers, affiliates, or subsidiaries, and our representation of the Company does not create an attorney-client relationship with any of them.",
    'the adjacent "our client is", which a letter opening more than one matter never writes',
  ],
  [
    "SET-106",
    "Settlement Agreement and Release",
    "This document is a settlement agreement and general release. It is not a covenant not to sue and shall not be construed as one.",
    "the covenant-side characterization only, never its mirror",
  ],
  [
    "COMM-231",
    "Subscription Terms",
    "Your subscription renews for a further term of one year at the then-current annual price of $1,188, billed annually, unless you cancel through the account page before the renewal date. We disclose the renewal term, price, and billing frequency clearly and conspicuously before we collect your billing information.",
    'the adverb in "automatically renews"',
  ],
  [
    "COMM-146",
    "Joint Venture Agreement",
    "The Venture's business is the design, manufacture, and sale of benchtop immunoassay readers in North America and the European Union. Neither Member may pursue that business outside the Venture in those territories during the Term.",
    'the of-phrase "business of the venture", never the possessive',
  ],
  [
    "MNA-055",
    "Transition Services Agreement",
    "SCHEDULE OF SERVICES. Payroll administration, twelve months, $18,400 per month. IT helpdesk, six months, $9,200 per month. Accounts payable processing, nine months, $6,750 per month.",
    "three spellings of one fact, conjoined, the first being the family's own title",
  ],
  [
    "RE-001",
    "Office Lease",
    "In addition to Base Rent, Tenant shall pay its Proportionate Share of real estate taxes, property insurance premiums, and common area maintenance charges for the Building, as Additional Rent, within thirty days after Landlord's statement.",
    'the words "triple net", which the clause never carries and only the lease title might',
  ],
  [
    "PRV-040",
    "Incident Response Plan",
    "The Company notifies the affected state attorneys general where the number of affected residents of a state exceeds that state's threshold, notifies the Secretary of Health and Human Services where a breach affects 500 or more individuals, and files an Item 1.05 Form 8-K where the incident is material.",
    'the singular "attorney general"',
  ],
  [
    "DISC-019",
    "Responses and Objections to Requests for Production",
    "Subject to and without waiving the foregoing objections, Defendant will produce all non-privileged responsive documents in its possession, custody, or control, and is withholding documents responsive to this request solely on the basis of the attorney-client privilege, which are identified on the privilege log served herewith.",
    "a withholding statement written any way but the plainest",
  ],
  [
    "GOV-071",
    "Article I — Purposes",
    "The corporation is organized exclusively for charitable and educational purposes within the meaning of Section 501(c)(3) of the Internal Revenue Code of 1986, as amended.",
    "three spellings of one fact, conjoined",
  ],
  [
    "EMP-148",
    "Disclosure Regarding Background Investigation",
    'Halverson Grid Services, Inc. may obtain information about you from a consumer reporting agency for employment purposes. Thus, you may be the subject of a "consumer report" which may include information about your character, general reputation, and mode of living.',
    "that the disclosure describe ITSELF as stand-alone, which a lawful one never does",
  ],
  [
    "MNA-039",
    "Disclosure Schedules",
    'These Disclosure Schedules are delivered by the Company pursuant to the Stock Purchase Agreement dated as of February 20, 2026 (the "Purchase Agreement"). The section numbers below correspond to the section numbers of the Purchase Agreement, and any matter disclosed in any section is deemed disclosed for the purposes of every other section to the extent its relevance is reasonably apparent.',
    'the literal heading "General Notes"',
  ],
  [
    "MNA-042",
    "Disclosure Schedules",
    "Nothing disclosed here is an admission that the matter is material, that it is required to be disclosed, or that it constitutes a breach of any representation. The inclusion of any dollar amount is not a representation that the amount is material.",
    'the negator "not" and the noun "admission", never "Nothing" and "representation"',
  ],
  [
    "ENG-012",
    "Contingency Fee Agreement",
    "The Firm will not represent the Client on appeal, in a bankruptcy, in a related insurance coverage dispute, or in any other matter unless the parties sign a separate agreement.",
    "a label, where the exclusion is written as a promise",
  ],
  [
    "RE-128",
    "Quitclaim Deed",
    "THE GRANTOR, Rosalind Amara Ferreira, conveys and quitclaims to THE GRANTEE all right, title, and interest that the Grantor may have in the property.",
    'the word "hereby", which the statutory short form does not contain',
  ],
  [
    "DISC-004",
    "Requests for Production",
    "Produce electronically stored information in single-page TIFF images with document-level extracted text, a Concordance-delimited load file, and the metadata fields listed in Appendix A; produce spreadsheets and audio in native format.",
    "the passive voice only, never the imperative the instruction is written in",
  ],
  [
    "DISC-017",
    "Responses and Objections to Requests for Production",
    "Defendant objects to this request as overbroad because it seeks documents from 2011, six years before the parties first did business, and as unduly burdensome because collecting them would require restoring forty backup tapes at a cost of approximately $180,000.",
    'the phrase "on the ground that", never the "as X because Y" practitioners write',
  ],
  [
    "DISC-018",
    "Responses and Objections to Requests for Production",
    "Defendant is withholding documents responsive to this request on the basis of the attorney-client privilege and the work-product doctrine, and has identified them on the privilege log served with these responses.",
    "the passive withholding statement only, never the active one",
  ],
  [
    "DISC-030",
    "Rule 26(f) Report",
    "The parties propose the following discovery plan: initial disclosures by June 1, 2026; fact discovery closing December 18, 2026; expert reports exchanged February 5, 2027; and a protective order and a Rule 502(d) order to be submitted by June 15, 2026.",
    "the rule's own vocabulary, where a report states its plan as deadlines",
  ],
  [
    "ENG-031",
    "Engagement Letter",
    "The representation ends when the transaction closes or when either of us terminates it in writing, whichever comes first. We will confirm the end of the representation in writing.",
    'the tokens "upon delivery" / "closing letter", which the sentence never uses',
  ],
  [
    "ENG-032",
    "Closing Letter",
    "This letter confirms that our representation of you in this matter has ended. We are not undertaking to advise you of any future change in the law.",
    'the adjacent "representation has ended", with the scope between noun and verb',
  ],
  [
    "GOV-144",
    "Indemnification Agreement",
    "Entitlement to indemnification is determined, at the Indemnitee's election, by a majority vote of the disinterested directors, by a committee of such directors designated by majority vote, or by Independent Counsel selected by the Indemnitee and approved by the Corporation.",
    'the noun phrase "determination of entitlement", never the sentence run the other way',
  ],
  [
    "GOV-146",
    "Indemnification Agreement",
    "The rights of the Indemnitee are not exclusive of any other rights the Indemnitee may have. The Corporation shall maintain directors and officers liability insurance covering the Indemnitee on terms no less favorable than the policy in effect on the date of this Agreement.",
    'the hyphenated "non-exclusive", never § 145(f)\'s own "not exclusive"',
  ],
  [
    "GOV-147",
    "Indemnification Agreement",
    "The rights of the Indemnitee survive the cessation of the Indemnitee's service and continue for so long as the Indemnitee may be subject to any Proceeding. No amendment to the certificate of incorporation or the bylaws may impair a right arising out of conduct occurring before the amendment.",
    'the verb forms only, never the nominal "cessation of service"',
  ],
  [
    "DISC-034",
    "Rule 26(f) Report",
    "The parties propose limits of twenty-five interrogatories and ten depositions per side, fact discovery closing December 18, 2026, dispositive motions due February 12, 2027, and a trial-ready date of June 7, 2027.",
    'the word "deadline", from a report that states its schedule by the events themselves',
  ],
  [
    "SET-025",
    "Litigation Hold Notice",
    "This notice is issued because the Company reasonably anticipates litigation arising out of the ceiling collapse at 1440 Fruitvale Avenue on November 14, 2025, and because a demand letter was received from counsel for the tenant on January 14, 2026.",
    "the past participle only, never the present tense a hold notice is written in",
  ],
  [
    "ENG-027",
    "Limited Scope Representation Agreement",
    "The lawyer will draft the petition, prepare the financial declaration, and appear at the status conference. The client will gather and provide bank statements, serve the petition, and appear at all other hearings.",
    'the words "will perform" from an agreement that LISTS the tasks, with its other pillar met by the family\'s own title',
  ],
  // ── Proved-silent rows for conjunctions whose vacuous pillar was left in
  // place: the surviving pillars carry the check, and these clauses are the
  // proof. See `pillar-vacuity.test.ts`.
  [
    "DISC-001",
    "Requests for Production",
    "Pursuant to Rule 34, Plaintiff requests that Defendant produce the documents described below within thirty (30) days after service of these requests.",
    "its surviving pillar, proved against the deadline a request actually states",
  ],
  [
    "DISC-007",
    "Interrogatories",
    "These interrogatories, including all discrete subparts, number twenty-two and are within the limit of twenty-five set by Rule 33(a)(1).",
    "its surviving pillar, proved against the limit recital",
  ],
  [
    "DISC-020",
    "Responses and Objections to Requests for Production",
    "Defendant will substantially complete its production of responsive documents on or before July 31, 2026.",
    "its surviving pillar, proved against a stated completion date",
  ],
  [
    "PLDG-009",
    "Answer",
    "IN THE UNITED STATES DISTRICT COURT FOR THE NORTHERN DISTRICT OF ILLINOIS. RIDGELINE AEROSPACE COMPONENTS, INC., Plaintiff, v. HALLORAN PRECISION CASTINGS, LLC, Defendant. Case No. 1:26-cv-04412. ANSWER AND AFFIRMATIVE DEFENSES.",
    "its surviving pillar, proved against a full caption and designation",
  ],
  [
    "PLDG-012",
    "Answer",
    "FIRST AFFIRMATIVE DEFENSE — STATUTE OF LIMITATIONS. The claim is barred by the applicable statute of limitations. SECOND AFFIRMATIVE DEFENSE — WAIVER. Plaintiff waived the claim by accepting performance for eleven months without objection.",
    "its surviving pillar, proved against separately stated defenses",
  ],
  [
    "EMP-101",
    "Arbitration Agreement",
    "The Company and the Employee each agree to arbitrate all claims arising out of the employment relationship, on the same terms, before a single neutral arbitrator. Claims of sexual harassment and sexual assault are excluded at the Employee's election under the Ending Forced Arbitration Act.",
    "its surviving pillar, proved against a mutual obligation with the EFAA carve-out",
  ],
  [
    "EMP-150",
    "Disclosure and Authorization",
    "I hereby authorize Halverson Grid Services, Inc. and its consumer reporting agency to obtain the consumer reports described in the disclosure above. Signature of applicant: ____________________ Date: ____________",
    "its surviving pillar, proved against a written authorization and signature line",
  ],
  [
    "HC-127",
    "Telehealth Informed Consent",
    "Your visit will be conducted by live two-way interactive audio and video through the practice's secure platform. If the video connection fails, the visit may continue by telephone with your agreement.",
    "its surviving pillar, proved against a described modality",
  ],
  [
    "ENG-006",
    "Engagement Letter",
    "You will pay an advance fee of $15,000, which we will deposit in our client trust account and withdraw only as fees are earned and costs incurred. Any unearned balance is refunded at the conclusion of the representation.",
    "its surviving pillar, proved against an advance fee and where it is held",
  ],
  [
    "ENG-008",
    "Engagement Letter",
    "You may terminate this engagement at any time by written notice. We may withdraw as the Rules of Professional Conduct permit and, if suit has been filed, with the court's permission. At the conclusion of the representation we will return your file to you on request.",
    "its surviving pillar, proved against termination, withdrawal, and file return",
  ],
  [
    "ENG-016",
    "Flat Fee Agreement",
    "The flat fee of $8,500 covers the preparation and filing of the trademark application, one office-action response, and the statement of use. It does not cover an appeal, an opposition, or a cancellation proceeding.",
    "its surviving pillar, proved against a stated scope of the flat fee",
  ],
  [
    "ENG-018",
    "Flat Fee Agreement",
    "The flat fee is paid in advance and will be deposited in our client trust account. We will withdraw it as the work described above is completed, in the milestones listed, and any unearned portion is refunded.",
    "its surviving pillar, proved against trust-account treatment of the advance",
  ],
  [
    "ENG-021",
    "Joint Representation Waiver",
    "You have each asked this firm to represent you in connection with the sale of the membership interests. We will represent both of you jointly, and each of you is our client for that purpose.",
    'the letter to say "the clients are", which a letter never does',
  ],
  [
    "ENG-024",
    "Joint Representation Waiver",
    "A joint representation lets us advance your shared objective efficiently and at lower cost than two firms would. The risk is that your interests are not identical: the allocation of the purchase price and of the indemnity may affect you differently, and if a disagreement arises we may have to withdraw from representing both of you. You are each entitled to separate counsel.",
    "its surviving pillar, proved against the advantages and the risks stated together",
  ],
  [
    "ENG-028",
    "Limited Scope Representation Agreement",
    "The limitation is reasonable in the circumstances of this matter because the client is able to appear and file on the client's own behalf, the issues are discrete, and the limitation makes representation affordable that would otherwise be beyond the client's means.",
    "its surviving pillar, proved against a stated reasonableness rationale",
  ],
  [
    "ENG-029",
    "Limited Scope Representation Agreement",
    "The client is responsible for everything not listed above, including meeting every filing deadline, serving papers, responding to discovery, and appearing at every hearing the lawyer is not appearing at.",
    "its surviving pillar, proved against the client's stated residual responsibility",
  ],
  [
    "DISC-024",
    "Privilege Log",
    "Each entry states the privilege asserted. Entry 1 is withheld in full on the basis of the attorney-client privilege; Entry 4 is withheld on the basis of the work-product doctrine.",
    "its surviving pillar, proved against an express claim of privilege",
  ],
  [
    "GOV-101",
    "Articles of Organization",
    "The name of the limited liability company is Harborlight Instruments LLC, which matches the name reserved with the Secretary of State under reservation number 2026-114820.",
    "its surviving pillar, proved against the entity name with its designator",
  ],
  [
    "COMM-237",
    "OEM Agreement",
    "Supplier grants OEM a non-exclusive license to incorporate the Licensed Software into the OEM Products and to distribute it solely as embedded in them. OEM may brand the OEM Products with its own marks and shall include the attribution notice set out in Exhibit B.",
    'the words "rebrand" or "under the OEM\'s brand" from a clause that grants the right plainly',
  ],
  [
    "PRV-102",
    "Biometric Data Consent",
    "We collect and use the hand-scan template for one purpose: to identify you when you clock in and out, so that your hours and your pay are recorded accurately. We do not use it for any other purpose.",
    'the phrase "specific purpose" from a form that states the purpose plainly',
  ],
  [
    "PRV-113",
    "SMS Program Terms",
    'By entering your mobile number and selecting "Sign up for texts," you consent to receive recurring automated marketing text messages. Consent is not a condition of any purchase.',
    'the first-person "I agree to receive" from a page that addresses the reader as "you"',
  ],
  [
    "EMP-110",
    "Sales Commission Plan",
    "A commission on an order booked before termination and collected within ninety days after termination is earned and paid in the payroll cycle following collection. No commission is earned on an order booked after the termination date.",
    "its surviving pillar, proved against a post-termination commission rule",
  ],
  [
    "EMP-121",
    "Relocation Agreement",
    "If the Employee resigns or is terminated for cause within twenty-four months of the relocation, the Employee shall repay the relocation benefits, prorated at 1/24th for each full month of service completed after the relocation date.",
    "its surviving pillar, proved against a repayment trigger and proration schedule",
  ],
  [
    "EST-426",
    "Cohabitation Agreement",
    "The parties are not married to each other, do not intend this Agreement to create a marriage or a common law marriage, and live together as domestic partners without any expectation of marital rights.",
    "its surviving pillar, proved against the non-marital status recital",
  ],
  [
    "BNK-127",
    "Deposit Account Control Agreement",
    "The Bank will comply with instructions originated by the Secured Party directing disposition of the funds in the Account without further consent by the Depositor, as Section 9-104(a)(2) of the Uniform Commercial Code requires.",
    "its surviving pillar, proved against § 9-104(a)(2) control language",
  ],
];
