/**
 * Extended-playbook manifest guard (spec-v6 full-catalog wiring).
 *
 * `playbooks/extended.json` is the served bundle of every v3 + v4 playbook —
 * the live pipeline fetches it so the matcher can route to those families and
 * their rules can fire. It is generated by `tools/build-extended-playbooks.ts`
 * from `src/playbooks/{v3,v4}/`. This test (a) fails on drift between the
 * committed manifest and a fresh regeneration, and (b) asserts every entry
 * validates against the public `PlaybookSchema` and matches a known rule-set
 * playbook id, so the served catalog can never silently fall out of sync.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import {
  collectExtendedPlaybooks,
  renderManifest,
  EXTENDED_MANIFEST_PATH,
} from "../../tools/build-extended-playbooks.js";
import { parsePlaybook, LAUNCH_PLAYBOOK_IDS } from "../../src/playbooks/index.js";
import { V3_RULES, V4_RULES } from "../../src/engine/index.js";

describe("extended playbook manifest", () => {
  it("the committed manifest matches a fresh regeneration (no drift)", () => {
    const committed = readFileSync(EXTENDED_MANIFEST_PATH, "utf8");
    const regenerated = renderManifest(collectExtendedPlaybooks());
    expect(
      committed,
      "playbooks/extended.json is stale — run `npm run playbooks:bundle` and commit",
    ).toBe(regenerated);
  });

  it("every manifest entry validates against PlaybookSchema", () => {
    const raw = JSON.parse(readFileSync(EXTENDED_MANIFEST_PATH, "utf8")) as unknown[];
    expect(raw.length).toBeGreaterThan(100);
    for (const entry of raw) {
      // Throws on a schema violation, naming the offending playbook.
      expect(() => parsePlaybook(entry)).not.toThrow();
    }
  });

  it("ids are unique and every v3/v4 rule has at least one servable gate-target playbook", () => {
    const raw = JSON.parse(readFileSync(EXTENDED_MANIFEST_PATH, "utf8")) as Array<{ id: string }>;
    const ids = new Set(raw.map((p) => p.id));
    expect(ids.size, "duplicate playbook ids in manifest").toBe(raw.length);

    // The invariant this wiring guarantees: every v3/v4 rule can actually
    // fire in the live pipeline — i.e. at least one of its applies_to_playbooks
    // is servable (in the extended manifest or the launch set). A rule may
    // also list aspirational ids (e.g. "baa-deep") that have no playbook; that
    // is harmless as long as one real target exists.
    const servable = new Set([...ids, ...LAUNCH_PLAYBOOK_IDS]);
    const unfireable: string[] = [];
    for (const r of [...V3_RULES, ...V4_RULES]) {
      const targets = r.applies_to_playbooks ?? [];
      if (targets.length > 0 && !targets.some((id) => servable.has(id))) {
        unfireable.push(r.id);
      }
    }
    expect(
      unfireable.sort(),
      `rules whose gate targets are all unservable (can never fire): ${unfireable.join(", ")}`,
    ).toEqual([]);
  });

  it("non-contract instruments suppress the generic contract rules", () => {
    // These documents are not contracts: they have no parties, governing law,
    // liability cap, termination, or IP-ownership clause. Each has a scoped
    // sibling in the 10-skip cohort that proves the intent — corporate
    // policies (aml, code-of-conduct, …); s-1-risk-factors ↔ 10-k-risk-factors;
    // healthcare-poa ↔ durable-poa-financial / advance-directive; ropa-art-30 ↔
    // dpia-art-35 — but shipped with empty rule_overrides, so the generic
    // contract rules fired as false positives on each.
    const raw = JSON.parse(readFileSync(EXTENDED_MANIFEST_PATH, "utf8")) as Array<{
      id: string;
      rule_overrides?: Record<string, { skip?: boolean }>;
    }>;
    const GENERIC = [
      "CHOICE-001",
      "CHOICE-003",
      "FIN-005",
      "IPDATA-001",
      "RISK-001",
      "RISK-005",
      "STRUCT-001",
      "STRUCT-002",
      // A document with no bargained terms has no defined-term glossary
      // either; every member of the cohort already skips this one, and
      // listing it keeps a new member from being admitted with ten of the
      // eleven.
      "STRUCT-004",
      "TERM-002",
      "TERM-005",
    ];
    for (const id of [
      "insider-trading-policy",
      "whistleblower-policy",
      "social-media-policy",
      "lobbying-policy",
      "s-1-risk-factors",
      "healthcare-poa",
      "ropa-art-30",
      "form-d-narrative",
      "ppm-narrative",
      "reg-a-plus-circular",
      "form-adv-brochure",
      "last-will-and-testament",
      "codicil",
      "informed-consent",
      "phi-authorization",
      "npp-acknowledgment",
      "hipaa-npp",
      "incident-notification",
      "section-83b-election",
      "ucc-1-financing-statement",
      "litigation-hold",
      "estoppel-certificate",
      "vendor-security-questionnaire",
      "demand-letter",
      "cease-and-desist",
      // The v5 catalog and the v6 law-practice packs shipped 135 new families
      // with empty `rule_overrides`, so every one of these — a policy, a plan,
      // a deed, a trust, a statutory notice, a one-sided consent, a closing
      // letter — drew the same false positives the cohort above exists to
      // suppress. A well-formed WARN notice is not missing its limitation of
      // liability.
      "acceptable-use-policy",
      "articles-of-organization",
      "background-check-disclosure",
      "biometric-consent",
      "board-resolution",
      "bonus-plan",
      "business-continuity-plan",
      "childrens-privacy-notice",
      "commission-plan",
      "cyber-insurance-policy",
      "dissolution-plan",
      "do-policy",
      "employee-stock-purchase-plan",
      "equity-incentive-plan",
      "export-control-policy",
      "franchise-disclosure-document",
      "information-security-policy",
      "irrevocable-trust",
      "media-release",
      "meeting-minutes",
      "preliminary-lien-notice",
      "proxy-statement-narrative",
      "quitclaim-deed",
      "reservation-of-rights-letter",
      "security-incident-response-plan",
      "sms-consent-disclosure",
      "special-needs-trust",
      "sweepstakes-official-rules",
      "telehealth-consent",
      "trust-amendment",
      "warn-notice",
      "warranty-deed",
      "termination-of-representation",
    ]) {
      const pb = raw.find((p) => p.id === id);
      expect(pb, `${id} missing from manifest`).toBeDefined();
      for (const rule of GENERIC) {
        expect(pb!.rule_overrides?.[rule]?.skip, `${id} should skip ${rule}`).toBe(true);
      }
    }
  });

  it("litigation papers suppress the contract rules the filing cohort already suppresses", () => {
    // A pleading, a discovery instrument, and a stipulated order are not
    // agreements at all: nobody signs them as a counterparty accepting terms,
    // and the whole commercial vocabulary — governing law, indemnity,
    // liability cap, termination, IP ownership, payment terms — is absent by
    // construction. `trial-motion`, `petition`, and `appellate-brief` already
    // held that line; the v5/v6 waves added fourteen more documents of the
    // same species and did not. Measured on a well-formed complaint, the
    // report was eleven findings, one of them critical, none of them about
    // the complaint.
    const raw = JSON.parse(readFileSync(EXTENDED_MANIFEST_PATH, "utf8")) as Array<{
      id: string;
      rule_overrides?: Record<string, { skip?: boolean }>;
    }>;
    const profileOf = (id: string) =>
      Object.entries(raw.find((p) => p.id === id)?.rule_overrides ?? {})
        .filter(([, v]) => v.skip)
        .map(([k]) => k)
        .sort();
    const FILING = profileOf("trial-motion");
    expect(FILING.length).toBe(53);
    for (const id of [
      "petition",
      "appellate-brief",
      "complaint",
      "answer",
      "interrogatories",
      "document-requests",
      "requests-for-admission",
      "discovery-responses",
      "privilege-log",
      "deposition-notice",
      "rule-26f-report",
      "arbitration-demand",
      "stipulation-of-dismissal",
      "protective-order-stipulated",
      "consent-judgment",
      "qdro",
    ]) {
      expect(profileOf(id), `${id} is not on the filing profile`).toEqual(FILING);
    }
  });
});
