/**
 * Guard: the committed scoreboard artifact must reflect the live catalog.
 *
 * `tools/accuracy/scoreboard.json` + `SCOREBOARD.md` are generated by
 * `npm run accuracy` and committed as a published trust artifact (spec-v5
 * §10). Its `catalog.rules` / `catalog.playbooks` counts are a snapshot of
 * the engine at generation time, so adding rules without re-running the
 * harness silently desyncs the published numbers from what ships. This guard
 * pins those two counts to the live engine so the drift surfaces locally (the
 * same discipline as the docs-link and case-sensitivity integrity guards),
 * with a one-line fix: `npm run accuracy`.
 *
 * It deliberately pins ONLY the catalog counts, not the scoreboard hash or
 * the precision/recall metrics — those legitimately move with the corpus and
 * are not part of "did someone forget to regenerate after a rule change."
 */
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { loadAccuracyDeps } from "./pipeline.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

describe("committed scoreboard is current with the live catalog", () => {
  it("scoreboard.json catalog counts match the live engine (run `npm run accuracy` if this fails)", async () => {
    const deps = await loadAccuracyDeps();
    const scoreboard = JSON.parse(
      await readFile(join(__dirname, "scoreboard.json"), "utf8"),
    ) as { catalog: { rules: number; playbooks: number } };

    expect(scoreboard.catalog.rules).toBe(deps.rules.length);
    expect(scoreboard.catalog.playbooks).toBe(
      deps.launchPlaybooks.length + deps.extendedPlaybooks.length,
    );
  });
});
