# Development Configuration for Vaulytica
# This file contains development-specific settings

environment: development
debug: true

# Model Configuration
model_name: claude-3-haiku-20240307
max_tokens: 4000
temperature: 0.0

# Logging
log_level: DEBUG

# Features
enable_rag: true
max_historical_incidents: 5
enable_cache: true

# Performance
batch_max_workers: 3
chunk_size: 50000

# Notification Thresholds
min_risk_score_notify: 0.5
notify_on_cache_hit: true

# Threat Intelligence
threat_feed_timeout: 30

