# Production Configuration for Vaulytica
# This file contains production-specific settings

environment: production
debug: false

# Model Configuration
model_name: claude-3-haiku-20240307
max_tokens: 4000
temperature: 0.0

# Logging
log_level: INFO

# Features
enable_rag: true
max_historical_incidents: 10
enable_cache: true

# Performance
batch_max_workers: 8
chunk_size: 50000

# Notification Thresholds
min_risk_score_notify: 0.8
notify_on_cache_hit: false

# Threat Intelligence
threat_feed_timeout: 10

# Note: Secrets should be provided via environment variables or secrets manager
# Do not store sensitive values in this file

