# Staging Configuration for Vaulytica
# This file contains staging-specific settings

environment: staging
debug: false

# Model Configuration
model_name: claude-3-haiku-20240307
max_tokens: 4000
temperature: 0.0

# Logging
log_level: INFO

# Features
enable_rag: true
max_historical_incidents: 8
enable_cache: true

# Performance
batch_max_workers: 5
chunk_size: 50000

# Notification Thresholds
min_risk_score_notify: 0.7
notify_on_cache_hit: false

# Threat Intelligence
threat_feed_timeout: 15

